name: gan-final-project
channels:
- pytorch
- defaults
dependencies:
- python=3.6
- pytorch=1.4.0
- scipy
- pip:
  - dominate==2.4.0
  - torchvision==0.5.0
  - Pillow==7.2.0
  - numpy==1.16.4
  - visdom==0.1.8
- opencv
- ghostscript
